apiVersion: apps/v1
kind: Deployment
metadata:
  name: Arale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Arale
  template:
    metadata:
      labels:
        app: Arale
    spec:
      containers:
      - image: okteto.dev/Arale:latest
        name: Arale
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "004b2dcc-98e1-4b6f-9668-6c53652adb5d"
        - name: Vless_Path
          value: "/vl123456"
        - name: Vmess_UUID
          value: "004b2dcc-98e1-4b6f-9668-6c53652adb5d"
        - name: Vmess_Path
          value: "/vm123456"
        - name: Share_Path
          value: "/v2link"
